'use strict';

// Define the `phonecatApp` module
var twitterApp = angular.module('twitterApp', []);

// Define the `PhoneListController` controller on the `phonecatApp` module
twitterApp.controller('suggestionsController', function suggestions($scope, suggestionsService) {
    $scope.suggestionUsers = _.shuffle(users).slice(0, 3)

    $scope.refreshUsers = function (index) {
        if (index === undefined ) {
            $scope.suggestionUsers = _.shuffle(users).slice(0, 3)
        } else {
          $scope.suggestionUsers[index] = _.shuffle(users)[0]
        }
    }


    // suggestionsService.getUsers().then(function (response) {
    //     $scope.suggestionUsers = response.data;
    // })
})

twitterApp.factory('suggestionsService', function suggestions($http, $q) {
    function getUsers() {
        return $q.resolve({data: [users[Math.round(Math.random() * 30)], users[Math.round(Math.random() * 30)], users[Math.round(Math.random() * 30)]]})
        // var randomOffset = Math.floor(Math.random() * 500);
        //return $http.get('https://api.github.com/users?since=' + randomOffset);
    }

    return {getUsers: getUsers};
})


var users = [
    {
        "login": "dkubb",
        "id": 133,
        "avatar_url": "https://avatars.githubusercontent.com/u/133?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/dkubb",
        "html_url": "https://github.com/dkubb",
        "followers_url": "https://api.github.com/users/dkubb/followers",
        "following_url": "https://api.github.com/users/dkubb/following{/other_user}",
        "gists_url": "https://api.github.com/users/dkubb/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/dkubb/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/dkubb/subscriptions",
        "organizations_url": "https://api.github.com/users/dkubb/orgs",
        "repos_url": "https://api.github.com/users/dkubb/repos",
        "events_url": "https://api.github.com/users/dkubb/events{/privacy}",
        "received_events_url": "https://api.github.com/users/dkubb/received_events",
        "type": "User",
        "site_admin": false
    },
    {
        "login": "jnicklas",
        "id": 134,
        "avatar_url": "https://avatars.githubusercontent.com/u/134?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/jnicklas",
        "html_url": "https://github.com/jnicklas",
        "followers_url": "https://api.github.com/users/jnicklas/followers",
        "following_url": "https://api.github.com/users/jnicklas/following{/other_user}",
        "gists_url": "https://api.github.com/users/jnicklas/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/jnicklas/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/jnicklas/subscriptions",
        "organizations_url": "https://api.github.com/users/jnicklas/orgs",
        "repos_url": "https://api.github.com/users/jnicklas/repos",
        "events_url": "https://api.github.com/users/jnicklas/events{/privacy}",
        "received_events_url": "https://api.github.com/users/jnicklas/received_events",
        "type": "User",
        "site_admin": false
    },
    {
        "login": "richcollins",
        "id": 135,
        "avatar_url": "https://avatars.githubusercontent.com/u/135?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/richcollins",
        "html_url": "https://github.com/richcollins",
        "followers_url": "https://api.github.com/users/richcollins/followers",
        "following_url": "https://api.github.com/users/richcollins/following{/other_user}",
        "gists_url": "https://api.github.com/users/richcollins/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/richcollins/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/richcollins/subscriptions",
        "organizations_url": "https://api.github.com/users/richcollins/orgs",
        "repos_url": "https://api.github.com/users/richcollins/repos",
        "events_url": "https://api.github.com/users/richcollins/events{/privacy}",
        "received_events_url": "https://api.github.com/users/richcollins/received_events",
        "type": "User",
        "site_admin": false
    },
    {
        "login": "simonjefford",
        "id": 136,
        "avatar_url": "https://avatars.githubusercontent.com/u/136?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/simonjefford",
        "html_url": "https://github.com/simonjefford",
        "followers_url": "https://api.github.com/users/simonjefford/followers",
        "following_url": "https://api.github.com/users/simonjefford/following{/other_user}",
        "gists_url": "https://api.github.com/users/simonjefford/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/simonjefford/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/simonjefford/subscriptions",
        "organizations_url": "https://api.github.com/users/simonjefford/orgs",
        "repos_url": "https://api.github.com/users/simonjefford/repos",
        "events_url": "https://api.github.com/users/simonjefford/events{/privacy}",
        "received_events_url": "https://api.github.com/users/simonjefford/received_events",
        "type": "User",
        "site_admin": false
    },
    {
        "login": "josh",
        "id": 137,
        "avatar_url": "https://avatars.githubusercontent.com/u/137?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/josh",
        "html_url": "https://github.com/josh",
        "followers_url": "https://api.github.com/users/josh/followers",
        "following_url": "https://api.github.com/users/josh/following{/other_user}",
        "gists_url": "https://api.github.com/users/josh/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/josh/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/josh/subscriptions",
        "organizations_url": "https://api.github.com/users/josh/orgs",
        "repos_url": "https://api.github.com/users/josh/repos",
        "events_url": "https://api.github.com/users/josh/events{/privacy}",
        "received_events_url": "https://api.github.com/users/josh/received_events",
        "type": "User",
        "site_admin": true
    },
    {
        "login": "stevedekorte",
        "id": 138,
        "avatar_url": "https://avatars.githubusercontent.com/u/138?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/stevedekorte",
        "html_url": "https://github.com/stevedekorte",
        "followers_url": "https://api.github.com/users/stevedekorte/followers",
        "following_url": "https://api.github.com/users/stevedekorte/following{/other_user}",
        "gists_url": "https://api.github.com/users/stevedekorte/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/stevedekorte/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/stevedekorte/subscriptions",
        "organizations_url": "https://api.github.com/users/stevedekorte/orgs",
        "repos_url": "https://api.github.com/users/stevedekorte/repos",
        "events_url": "https://api.github.com/users/stevedekorte/events{/privacy}",
        "received_events_url": "https://api.github.com/users/stevedekorte/received_events",
        "type": "User",
        "site_admin": false
    },
    {
        "login": "chneukirchen",
        "id": 139,
        "avatar_url": "https://avatars.githubusercontent.com/u/139?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/chneukirchen",
        "html_url": "https://github.com/chneukirchen",
        "followers_url": "https://api.github.com/users/chneukirchen/followers",
        "following_url": "https://api.github.com/users/chneukirchen/following{/other_user}",
        "gists_url": "https://api.github.com/users/chneukirchen/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/chneukirchen/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/chneukirchen/subscriptions",
        "organizations_url": "https://api.github.com/users/chneukirchen/orgs",
        "repos_url": "https://api.github.com/users/chneukirchen/repos",
        "events_url": "https://api.github.com/users/chneukirchen/events{/privacy}",
        "received_events_url": "https://api.github.com/users/chneukirchen/received_events",
        "type": "User",
        "site_admin": false
    },
    {
        "login": "cheapRoc",
        "id": 140,
        "avatar_url": "https://avatars.githubusercontent.com/u/140?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/cheapRoc",
        "html_url": "https://github.com/cheapRoc",
        "followers_url": "https://api.github.com/users/cheapRoc/followers",
        "following_url": "https://api.github.com/users/cheapRoc/following{/other_user}",
        "gists_url": "https://api.github.com/users/cheapRoc/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/cheapRoc/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/cheapRoc/subscriptions",
        "organizations_url": "https://api.github.com/users/cheapRoc/orgs",
        "repos_url": "https://api.github.com/users/cheapRoc/repos",
        "events_url": "https://api.github.com/users/cheapRoc/events{/privacy}",
        "received_events_url": "https://api.github.com/users/cheapRoc/received_events",
        "type": "User",
        "site_admin": false
    },
    {
        "login": "technomancy",
        "id": 141,
        "avatar_url": "https://avatars.githubusercontent.com/u/141?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/technomancy",
        "html_url": "https://github.com/technomancy",
        "followers_url": "https://api.github.com/users/technomancy/followers",
        "following_url": "https://api.github.com/users/technomancy/following{/other_user}",
        "gists_url": "https://api.github.com/users/technomancy/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/technomancy/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/technomancy/subscriptions",
        "organizations_url": "https://api.github.com/users/technomancy/orgs",
        "repos_url": "https://api.github.com/users/technomancy/repos",
        "events_url": "https://api.github.com/users/technomancy/events{/privacy}",
        "received_events_url": "https://api.github.com/users/technomancy/received_events",
        "type": "User",
        "site_admin": false
    },
    {
        "login": "kenphused",
        "id": 142,
        "avatar_url": "https://avatars.githubusercontent.com/u/142?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/kenphused",
        "html_url": "https://github.com/kenphused",
        "followers_url": "https://api.github.com/users/kenphused/followers",
        "following_url": "https://api.github.com/users/kenphused/following{/other_user}",
        "gists_url": "https://api.github.com/users/kenphused/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/kenphused/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/kenphused/subscriptions",
        "organizations_url": "https://api.github.com/users/kenphused/orgs",
        "repos_url": "https://api.github.com/users/kenphused/repos",
        "events_url": "https://api.github.com/users/kenphused/events{/privacy}",
        "received_events_url": "https://api.github.com/users/kenphused/received_events",
        "type": "User",
        "site_admin": false
    },
    {
        "login": "rubyist",
        "id": 143,
        "avatar_url": "https://avatars.githubusercontent.com/u/143?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/rubyist",
        "html_url": "https://github.com/rubyist",
        "followers_url": "https://api.github.com/users/rubyist/followers",
        "following_url": "https://api.github.com/users/rubyist/following{/other_user}",
        "gists_url": "https://api.github.com/users/rubyist/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/rubyist/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/rubyist/subscriptions",
        "organizations_url": "https://api.github.com/users/rubyist/orgs",
        "repos_url": "https://api.github.com/users/rubyist/repos",
        "events_url": "https://api.github.com/users/rubyist/events{/privacy}",
        "received_events_url": "https://api.github.com/users/rubyist/received_events",
        "type": "User",
        "site_admin": true
    },
    {
        "login": "ogc",
        "id": 144,
        "avatar_url": "https://avatars.githubusercontent.com/u/144?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ogc",
        "html_url": "https://github.com/ogc",
        "followers_url": "https://api.github.com/users/ogc/followers",
        "following_url": "https://api.github.com/users/ogc/following{/other_user}",
        "gists_url": "https://api.github.com/users/ogc/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/ogc/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/ogc/subscriptions",
        "organizations_url": "https://api.github.com/users/ogc/orgs",
        "repos_url": "https://api.github.com/users/ogc/repos",
        "events_url": "https://api.github.com/users/ogc/events{/privacy}",
        "received_events_url": "https://api.github.com/users/ogc/received_events",
        "type": "Organization",
        "site_admin": false
    },
    {
        "login": "lazyatom",
        "id": 145,
        "avatar_url": "https://avatars.githubusercontent.com/u/145?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/lazyatom",
        "html_url": "https://github.com/lazyatom",
        "followers_url": "https://api.github.com/users/lazyatom/followers",
        "following_url": "https://api.github.com/users/lazyatom/following{/other_user}",
        "gists_url": "https://api.github.com/users/lazyatom/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/lazyatom/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/lazyatom/subscriptions",
        "organizations_url": "https://api.github.com/users/lazyatom/orgs",
        "repos_url": "https://api.github.com/users/lazyatom/repos",
        "events_url": "https://api.github.com/users/lazyatom/events{/privacy}",
        "received_events_url": "https://api.github.com/users/lazyatom/received_events",
        "type": "User",
        "site_admin": false
    },
    {
        "login": "jdhuntington",
        "id": 147,
        "avatar_url": "https://avatars.githubusercontent.com/u/147?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/jdhuntington",
        "html_url": "https://github.com/jdhuntington",
        "followers_url": "https://api.github.com/users/jdhuntington/followers",
        "following_url": "https://api.github.com/users/jdhuntington/following{/other_user}",
        "gists_url": "https://api.github.com/users/jdhuntington/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/jdhuntington/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/jdhuntington/subscriptions",
        "organizations_url": "https://api.github.com/users/jdhuntington/orgs",
        "repos_url": "https://api.github.com/users/jdhuntington/repos",
        "events_url": "https://api.github.com/users/jdhuntington/events{/privacy}",
        "received_events_url": "https://api.github.com/users/jdhuntington/received_events",
        "type": "User",
        "site_admin": false
    },
    {
        "login": "nwebb",
        "id": 148,
        "avatar_url": "https://avatars.githubusercontent.com/u/148?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/nwebb",
        "html_url": "https://github.com/nwebb",
        "followers_url": "https://api.github.com/users/nwebb/followers",
        "following_url": "https://api.github.com/users/nwebb/following{/other_user}",
        "gists_url": "https://api.github.com/users/nwebb/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/nwebb/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/nwebb/subscriptions",
        "organizations_url": "https://api.github.com/users/nwebb/orgs",
        "repos_url": "https://api.github.com/users/nwebb/repos",
        "events_url": "https://api.github.com/users/nwebb/events{/privacy}",
        "received_events_url": "https://api.github.com/users/nwebb/received_events",
        "type": "User",
        "site_admin": false
    },
    {
        "login": "nsutton",
        "id": 149,
        "avatar_url": "https://avatars.githubusercontent.com/u/149?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/nsutton",
        "html_url": "https://github.com/nsutton",
        "followers_url": "https://api.github.com/users/nsutton/followers",
        "following_url": "https://api.github.com/users/nsutton/following{/other_user}",
        "gists_url": "https://api.github.com/users/nsutton/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/nsutton/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/nsutton/subscriptions",
        "organizations_url": "https://api.github.com/users/nsutton/orgs",
        "repos_url": "https://api.github.com/users/nsutton/repos",
        "events_url": "https://api.github.com/users/nsutton/events{/privacy}",
        "received_events_url": "https://api.github.com/users/nsutton/received_events",
        "type": "User",
        "site_admin": false
    },
    {
        "login": "sevenwire",
        "id": 150,
        "avatar_url": "https://avatars.githubusercontent.com/u/150?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/sevenwire",
        "html_url": "https://github.com/sevenwire",
        "followers_url": "https://api.github.com/users/sevenwire/followers",
        "following_url": "https://api.github.com/users/sevenwire/following{/other_user}",
        "gists_url": "https://api.github.com/users/sevenwire/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/sevenwire/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/sevenwire/subscriptions",
        "organizations_url": "https://api.github.com/users/sevenwire/orgs",
        "repos_url": "https://api.github.com/users/sevenwire/repos",
        "events_url": "https://api.github.com/users/sevenwire/events{/privacy}",
        "received_events_url": "https://api.github.com/users/sevenwire/received_events",
        "type": "Organization",
        "site_admin": false
    },
    {
        "login": "brandonarbini",
        "id": 151,
        "avatar_url": "https://avatars.githubusercontent.com/u/151?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/brandonarbini",
        "html_url": "https://github.com/brandonarbini",
        "followers_url": "https://api.github.com/users/brandonarbini/followers",
        "following_url": "https://api.github.com/users/brandonarbini/following{/other_user}",
        "gists_url": "https://api.github.com/users/brandonarbini/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/brandonarbini/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/brandonarbini/subscriptions",
        "organizations_url": "https://api.github.com/users/brandonarbini/orgs",
        "repos_url": "https://api.github.com/users/brandonarbini/repos",
        "events_url": "https://api.github.com/users/brandonarbini/events{/privacy}",
        "received_events_url": "https://api.github.com/users/brandonarbini/received_events",
        "type": "User",
        "site_admin": false
    },
    {
        "login": "al3x",
        "id": 152,
        "avatar_url": "https://avatars.githubusercontent.com/u/152?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/al3x",
        "html_url": "https://github.com/al3x",
        "followers_url": "https://api.github.com/users/al3x/followers",
        "following_url": "https://api.github.com/users/al3x/following{/other_user}",
        "gists_url": "https://api.github.com/users/al3x/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/al3x/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/al3x/subscriptions",
        "organizations_url": "https://api.github.com/users/al3x/orgs",
        "repos_url": "https://api.github.com/users/al3x/repos",
        "events_url": "https://api.github.com/users/al3x/events{/privacy}",
        "received_events_url": "https://api.github.com/users/al3x/received_events",
        "type": "User",
        "site_admin": false
    },
    {
        "login": "toolmantim",
        "id": 153,
        "avatar_url": "https://avatars.githubusercontent.com/u/153?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/toolmantim",
        "html_url": "https://github.com/toolmantim",
        "followers_url": "https://api.github.com/users/toolmantim/followers",
        "following_url": "https://api.github.com/users/toolmantim/following{/other_user}",
        "gists_url": "https://api.github.com/users/toolmantim/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/toolmantim/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/toolmantim/subscriptions",
        "organizations_url": "https://api.github.com/users/toolmantim/orgs",
        "repos_url": "https://api.github.com/users/toolmantim/repos",
        "events_url": "https://api.github.com/users/toolmantim/events{/privacy}",
        "received_events_url": "https://api.github.com/users/toolmantim/received_events",
        "type": "User",
        "site_admin": false
    },
    {
        "login": "nicksieger",
        "id": 154,
        "avatar_url": "https://avatars.githubusercontent.com/u/154?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/nicksieger",
        "html_url": "https://github.com/nicksieger",
        "followers_url": "https://api.github.com/users/nicksieger/followers",
        "following_url": "https://api.github.com/users/nicksieger/following{/other_user}",
        "gists_url": "https://api.github.com/users/nicksieger/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/nicksieger/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/nicksieger/subscriptions",
        "organizations_url": "https://api.github.com/users/nicksieger/orgs",
        "repos_url": "https://api.github.com/users/nicksieger/repos",
        "events_url": "https://api.github.com/users/nicksieger/events{/privacy}",
        "received_events_url": "https://api.github.com/users/nicksieger/received_events",
        "type": "User",
        "site_admin": false
    },
    {
        "login": "jicksta",
        "id": 155,
        "avatar_url": "https://avatars.githubusercontent.com/u/155?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/jicksta",
        "html_url": "https://github.com/jicksta",
        "followers_url": "https://api.github.com/users/jicksta/followers",
        "following_url": "https://api.github.com/users/jicksta/following{/other_user}",
        "gists_url": "https://api.github.com/users/jicksta/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/jicksta/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/jicksta/subscriptions",
        "organizations_url": "https://api.github.com/users/jicksta/orgs",
        "repos_url": "https://api.github.com/users/jicksta/repos",
        "events_url": "https://api.github.com/users/jicksta/events{/privacy}",
        "received_events_url": "https://api.github.com/users/jicksta/received_events",
        "type": "User",
        "site_admin": false
    },
    {
        "login": "joshsusser",
        "id": 156,
        "avatar_url": "https://avatars.githubusercontent.com/u/156?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/joshsusser",
        "html_url": "https://github.com/joshsusser",
        "followers_url": "https://api.github.com/users/joshsusser/followers",
        "following_url": "https://api.github.com/users/joshsusser/following{/other_user}",
        "gists_url": "https://api.github.com/users/joshsusser/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/joshsusser/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/joshsusser/subscriptions",
        "organizations_url": "https://api.github.com/users/joshsusser/orgs",
        "repos_url": "https://api.github.com/users/joshsusser/repos",
        "events_url": "https://api.github.com/users/joshsusser/events{/privacy}",
        "received_events_url": "https://api.github.com/users/joshsusser/received_events",
        "type": "User",
        "site_admin": false
    },
    {
        "login": "jcrosby",
        "id": 157,
        "avatar_url": "https://avatars.githubusercontent.com/u/157?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/jcrosby",
        "html_url": "https://github.com/jcrosby",
        "followers_url": "https://api.github.com/users/jcrosby/followers",
        "following_url": "https://api.github.com/users/jcrosby/following{/other_user}",
        "gists_url": "https://api.github.com/users/jcrosby/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/jcrosby/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/jcrosby/subscriptions",
        "organizations_url": "https://api.github.com/users/jcrosby/orgs",
        "repos_url": "https://api.github.com/users/jcrosby/repos",
        "events_url": "https://api.github.com/users/jcrosby/events{/privacy}",
        "received_events_url": "https://api.github.com/users/jcrosby/received_events",
        "type": "User",
        "site_admin": false
    },
    {
        "login": "thewoolleyman",
        "id": 158,
        "avatar_url": "https://avatars.githubusercontent.com/u/158?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/thewoolleyman",
        "html_url": "https://github.com/thewoolleyman",
        "followers_url": "https://api.github.com/users/thewoolleyman/followers",
        "following_url": "https://api.github.com/users/thewoolleyman/following{/other_user}",
        "gists_url": "https://api.github.com/users/thewoolleyman/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/thewoolleyman/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/thewoolleyman/subscriptions",
        "organizations_url": "https://api.github.com/users/thewoolleyman/orgs",
        "repos_url": "https://api.github.com/users/thewoolleyman/repos",
        "events_url": "https://api.github.com/users/thewoolleyman/events{/privacy}",
        "received_events_url": "https://api.github.com/users/thewoolleyman/received_events",
        "type": "User",
        "site_admin": false
    },
    {
        "login": "technicalpickles",
        "id": 159,
        "avatar_url": "https://avatars.githubusercontent.com/u/159?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/technicalpickles",
        "html_url": "https://github.com/technicalpickles",
        "followers_url": "https://api.github.com/users/technicalpickles/followers",
        "following_url": "https://api.github.com/users/technicalpickles/following{/other_user}",
        "gists_url": "https://api.github.com/users/technicalpickles/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/technicalpickles/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/technicalpickles/subscriptions",
        "organizations_url": "https://api.github.com/users/technicalpickles/orgs",
        "repos_url": "https://api.github.com/users/technicalpickles/repos",
        "events_url": "https://api.github.com/users/technicalpickles/events{/privacy}",
        "received_events_url": "https://api.github.com/users/technicalpickles/received_events",
        "type": "User",
        "site_admin": true
    },
    {
        "login": "halbtuerke",
        "id": 160,
        "avatar_url": "https://avatars.githubusercontent.com/u/160?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/halbtuerke",
        "html_url": "https://github.com/halbtuerke",
        "followers_url": "https://api.github.com/users/halbtuerke/followers",
        "following_url": "https://api.github.com/users/halbtuerke/following{/other_user}",
        "gists_url": "https://api.github.com/users/halbtuerke/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/halbtuerke/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/halbtuerke/subscriptions",
        "organizations_url": "https://api.github.com/users/halbtuerke/orgs",
        "repos_url": "https://api.github.com/users/halbtuerke/repos",
        "events_url": "https://api.github.com/users/halbtuerke/events{/privacy}",
        "received_events_url": "https://api.github.com/users/halbtuerke/received_events",
        "type": "User",
        "site_admin": false
    },
    {
        "login": "ryanb",
        "id": 161,
        "avatar_url": "https://avatars.githubusercontent.com/u/161?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ryanb",
        "html_url": "https://github.com/ryanb",
        "followers_url": "https://api.github.com/users/ryanb/followers",
        "following_url": "https://api.github.com/users/ryanb/following{/other_user}",
        "gists_url": "https://api.github.com/users/ryanb/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/ryanb/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/ryanb/subscriptions",
        "organizations_url": "https://api.github.com/users/ryanb/orgs",
        "repos_url": "https://api.github.com/users/ryanb/repos",
        "events_url": "https://api.github.com/users/ryanb/events{/privacy}",
        "received_events_url": "https://api.github.com/users/ryanb/received_events",
        "type": "User",
        "site_admin": false
    },
    {
        "login": "cnix",
        "id": 162,
        "avatar_url": "https://avatars.githubusercontent.com/u/162?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/cnix",
        "html_url": "https://github.com/cnix",
        "followers_url": "https://api.github.com/users/cnix/followers",
        "following_url": "https://api.github.com/users/cnix/following{/other_user}",
        "gists_url": "https://api.github.com/users/cnix/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/cnix/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/cnix/subscriptions",
        "organizations_url": "https://api.github.com/users/cnix/orgs",
        "repos_url": "https://api.github.com/users/cnix/repos",
        "events_url": "https://api.github.com/users/cnix/events{/privacy}",
        "received_events_url": "https://api.github.com/users/cnix/received_events",
        "type": "User",
        "site_admin": false
    },
    {
        "login": "tpitale",
        "id": 163,
        "avatar_url": "https://avatars.githubusercontent.com/u/163?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/tpitale",
        "html_url": "https://github.com/tpitale",
        "followers_url": "https://api.github.com/users/tpitale/followers",
        "following_url": "https://api.github.com/users/tpitale/following{/other_user}",
        "gists_url": "https://api.github.com/users/tpitale/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/tpitale/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/tpitale/subscriptions",
        "organizations_url": "https://api.github.com/users/tpitale/orgs",
        "repos_url": "https://api.github.com/users/tpitale/repos",
        "events_url": "https://api.github.com/users/tpitale/events{/privacy}",
        "received_events_url": "https://api.github.com/users/tpitale/received_events",
        "type": "User",
        "site_admin": false
    }
]
